import {
  initiateUserControlledWalletsClient,
  Blockchain,
  type CircleUserControlledWalletsClient,
} from "@circle-fin/user-controlled-wallets";

// Circle User-Controlled Wallets + Social Login — the "sign in with Google, get a wallet"
// flow. Deliberately a *different* Circle product from wallets.ts's Developer-Controlled
// Wallets: there, this app holds the signing key server-side (via an entity secret) and can
// send on the owner's behalf; here, Circle splits the key material with the *user* (via a PIN
// the user sets in a Circle-hosted widget), so this app never has standalone signing authority
// over these wallets — every transaction needs the user present. That's a deliberate tradeoff,
// not a gap: it's what makes "no seed phrase, no wallet extension, just sign in" possible.
//
// Almost everything here happens across a client/server boundary the browser SDK mediates:
// - `deviceId` is generated by the frontend's `W3SSdk.getDeviceId()` (never here).
// - `userToken`/`encryptionKey` come from the frontend's completed Google OAuth handshake
//   (`W3SSdk.performLogin`), not from anything this module produces.
// - The PIN itself is entered in Circle's own hosted iframe UI, never touches this app at all.
// This module is only the handful of calls that *require* the API key (device-token issuance,
// wallet/PIN-challenge creation, listing wallets, reading balances) — see
// apps/web/src/app/api/circle/social/* for where these get called from, and
// create-wallet-social-login.md in Circle's own circlefin/skills repo for the reference this
// was built against.

export function createSocialWalletsClient(apiKey: string): CircleUserControlledWalletsClient {
  return initiateUserControlledWalletsClient({ apiKey });
}

/** The chains this app requests a wallet on for every social-login user. EOA, not SCA — SCA
 * isn't supported for Solana (confirmed via Circle's own docs), and a single account-type
 * across all four keeps this simpler than branching per chain for no real benefit here. */
export const SOCIAL_LOGIN_BLOCKCHAINS = [
  Blockchain.ArcTestnet,
  Blockchain.BaseSepolia,
  Blockchain.EthSepolia,
  Blockchain.SolDevnet,
] as const;

export interface DeviceTokenResult {
  deviceToken: string;
  deviceEncryptionKey: string;
}

export async function createSocialLoginDeviceToken(client: CircleUserControlledWalletsClient, deviceId: string): Promise<DeviceTokenResult> {
  const response = await client.createDeviceTokenForSocialLogin({ deviceId });
  const data = response.data;
  if (!data?.deviceToken || !data.deviceEncryptionKey) throw new Error("Circle: device token response missing deviceToken/deviceEncryptionKey");
  return { deviceToken: data.deviceToken, deviceEncryptionKey: data.deviceEncryptionKey };
}

export interface SocialWallet {
  id: string;
  address: string;
  blockchain: string;
}

export async function listUserWallets(client: CircleUserControlledWalletsClient, userToken: string): Promise<SocialWallet[]> {
  const response = await client.listWallets({ userToken });
  return (response.data?.wallets ?? []).map((w) => ({ id: w.id, address: w.address, blockchain: w.blockchain }));
}

export type InitializeUserResult = { status: "challenge"; challengeId: string } | { status: "already-provisioned"; wallets: SocialWallet[] };

/** Circle error code for "this user already has a PIN/wallets set up" — createUserPinWithWallets
 * rejects a second call for the same user with this code rather than returning the existing
 * challenge, confirmed against Circle's own circlefin/skills reference implementation. */
const USER_ALREADY_INITIALIZED_CODE = 155106;

function isAlreadyInitializedError(err: unknown): boolean {
  return typeof err === "object" && err !== null && "code" in err && (err as { code: unknown }).code === USER_ALREADY_INITIALIZED_CODE;
}

/** Creates a PIN-setup challenge + wallets on every chain in SOCIAL_LOGIN_BLOCKCHAINS for a
 * freshly-Google-authenticated user, or — if this Circle user already went through PIN setup
 * before (returning user) — falls back to listing their existing wallets instead of erroring. */
export async function initializeUserWallets(client: CircleUserControlledWalletsClient, userToken: string): Promise<InitializeUserResult> {
  try {
    const response = await client.createUserPinWithWallets({
      userToken,
      blockchains: [...SOCIAL_LOGIN_BLOCKCHAINS],
      accountType: "EOA",
    });
    const challengeId = response.data?.challengeId;
    if (!challengeId) throw new Error("Circle: createUserPinWithWallets returned no challengeId");
    return { status: "challenge", challengeId };
  } catch (err) {
    if (!isAlreadyInitializedError(err)) throw err;
    return { status: "already-provisioned", wallets: await listUserWallets(client, userToken) };
  }
}

export interface SocialWalletBalance {
  walletId: string;
  amountUsdc: string;
}

export async function getUserWalletBalance(client: CircleUserControlledWalletsClient, userToken: string, walletId: string): Promise<SocialWalletBalance> {
  const response = await client.getWalletTokenBalance({ userToken, walletId });
  const usdc = (response.data?.tokenBalances ?? []).find((b) => b.token.isNative || b.token.symbol === "USDC");
  return { walletId, amountUsdc: usdc?.amount ?? "0" };
}

// --- Signing/execution: the User-Controlled counterpart to on-chain writes. Every one of these
// returns only a challengeId — the actual signature/execution never touches this app's server.
// The frontend calls `sdk.execute(challengeId)`, the user approves via their PIN in Circle's
// hosted widget, and the result comes back to the *browser* directly (or, for contract
// execution, is fetched via a follow-up poll — see getContractExecutionOutcome below).

export interface SignChallengeResult {
  challengeId: string;
}

// --- Contract execution: the API this app's on-chain writes actually need. Circle's own docs
// (developers.circle.com/wallets/user-controlled/...) are explicit that `signTransaction` is for
// *offchain* signing only ("doesn't cost gas") and that onchain transactions must go through a
// dedicated create-transaction API instead — confirmed by `ContractExecutionBlockchain`'s type
// comment ("contract execution is only supported on specific blockchains") being a genuinely
// different, narrower list than the general-purpose `Blockchain` enum `SOCIAL_LOGIN_BLOCKCHAINS`
// above uses, though it does include Arc/Base/Eth Sepolia.
// `createUserTransactionContractExecutionChallenge` (unlike `signTransaction`) has Circle itself
// construct, sign, *and broadcast* the transaction — this app never sees a raw signed tx to
// broadcast itself, only a challengeId to route through the PIN widget.

export interface ContractExecutionInput {
  walletId: string;
  contractAddress: string;
  /** ABI-encoded calldata (from viem's `encodeFunctionData`) — passed through as Circle's
   * `callData` field rather than translated into its alternative `abiFunctionSignature` +
   * `abiParameters` shape, since viem already produces this correctly for any argument type. */
  callData: `0x${string}`;
  /** Native-token amount to send alongside the call, in the chain's human-readable decimal
   * units (not wei) — Circle's own `amount` field shape. Omitted entirely for the common case
   * of a non-payable call. */
  amount?: string;
}

export async function requestContractExecution(
  client: CircleUserControlledWalletsClient,
  userToken: string,
  input: ContractExecutionInput,
): Promise<SignChallengeResult> {
  const response = await client.createUserTransactionContractExecutionChallenge({
    userToken,
    walletId: input.walletId,
    contractAddress: input.contractAddress,
    callData: input.callData,
    amount: input.amount,
    fee: { type: "level", config: { feeLevel: "MEDIUM" } },
  });
  const challengeId = response.data?.challengeId;
  if (!challengeId) throw new Error("Circle: createUserTransactionContractExecutionChallenge returned no challengeId");
  return { challengeId };
}

export type ChallengeOutcome =
  | { state: "pending" }
  | { state: "complete"; txHash: string }
  | { state: "failed"; errorMessage: string };

/** Polls a contract-execution challenge to completion: first the challenge itself (does
 * `execute()`'s PIN approval + Circle's own submission have a result yet?), then — once
 * COMPLETE — the transaction Circle created for it (has *that* landed on chain yet?). A
 * completed challenge only tells us Circle accepted the request; `correlationIds[0]` is the
 * transaction id we then poll separately for the actual txHash, per `Challenge`'s own doc
 * comment ("For types CREATE_TRANSACTION... the transaction id associated with the request"). */
export async function getContractExecutionOutcome(client: CircleUserControlledWalletsClient, userToken: string, challengeId: string): Promise<ChallengeOutcome> {
  const challengeResponse = await client.getUserChallenge({ userToken, challengeId });
  const challenge = challengeResponse.data?.challenge;
  if (!challenge) return { state: "pending" };

  if (challenge.status === "FAILED" || challenge.status === "EXPIRED") {
    return { state: "failed", errorMessage: challenge.errorMessage ?? `Challenge ${challenge.status.toLowerCase()}` };
  }
  if (challenge.status !== "COMPLETE") return { state: "pending" };

  const transactionId = challenge.correlationIds?.[0];
  if (!transactionId) return { state: "failed", errorMessage: "Challenge completed with no associated transaction id" };

  const transactionResponse = await client.getTransaction({ userToken, id: transactionId });
  const transaction = transactionResponse.data?.transaction;
  if (!transaction) return { state: "pending" };

  if (transaction.state === "FAILED" || transaction.state === "DENIED" || transaction.state === "CANCELLED") {
    return { state: "failed", errorMessage: `Transaction ${transaction.state.toLowerCase()}` };
  }
  if (!transaction.txHash) return { state: "pending" };
  return { state: "complete", txHash: transaction.txHash };
}
